{% set name = "libusb-package" %}
{% set version = "1.0.26.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libusb-package-{{ version }}.tar.gz
  sha256: 5a586744a59e3870791c28f964568e211f5f44bb398ccb51b25f3565dd4666ad

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools-scm
    - tomli
  run:
    - importlib-resources  # [py<37]
    - python

test:
  imports:
    - libusb_package
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyocd/libusb-package
  summary: Package containing libusb so it can be installed via Python package managers
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rudispr
